import os
import re

from cognition.language_cortex import normalize_language


def _sanitize(text, fallback="Untitled"):
    text = (text or "").strip()
    text = re.sub(r"[^A-Za-z0-9 _\-\.]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:60] or fallback


def _slug(text):
    return re.sub(r"[^a-z0-9_\-]+", "-", (text or "").lower()).strip("-") or "app"


class AppBuilder:
    """Brain-owned application generator.

    Builds full, runnable projects (static websites, Flask web apps, CLI
    tools) deterministically and ONLY for programming languages the brain has
    already learned. No external LLM is involved."""

    def __init__(self, language_cortex, output_dir="generated_apps"):
        self.cortex = language_cortex
        self.output_dir = output_dir

    # ---------------------------------------------------------------
    # Gates
    # ---------------------------------------------------------------

    def _gate(self, language):
        lang = normalize_language(language)
        if not self.cortex.knows(lang):
            return False, lang, f"I have not learned {lang} yet. Ask me to learn it from the internet first."
        return True, lang, None

    def _project_path(self, name):
        folder = os.path.join(self.output_dir, _slug(name))
        os.makedirs(folder, exist_ok=True)
        return folder

    # ---------------------------------------------------------------
    # Static website (single self-contained HTML file)
    # ---------------------------------------------------------------

    def build_website(self, name="My Website", title="My Website", sections=None, theme="light"):
        ok, lang, err = self._gate("html")
        if not ok:
            return False, err
        name = _sanitize(name, "My Website")
        title = _sanitize(title, name)
        theme = "dark" if str(theme).lower() == "dark" else "light"
        sections = [s.strip() for s in (sections or "").split(";") if s.strip()] or ["Welcome"]
        nav_links = "".join(
            f'<a href="#{_slug(s)}">{_sanitize(s, "Section")}</a>' for s in sections
        )
        section_blocks = "".join(
            f'<section id="{_slug(s)}"><h2>{_sanitize(s, "Section")}</h2>'
            f'<p>This is the {_sanitize(s, "section")} section of {title}.</p></section>'
            for s in sections
        )
        bg = "#1e1e2e" if theme == "dark" else "#f4f4f9"
        fg = "#e6e6ef" if theme == "dark" else "#22223b"
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{ margin: 0; font-family: -apple-system, Segoe UI, Roboto, sans-serif;
         background: {bg}; color: {fg}; }}
  header {{ padding: 1.2rem 2rem; display: flex; justify-content: space-between;
           align-items: center; border-bottom: 2px solid rgba(128,128,160,.3); }}
  nav a {{ color: {fg}; margin-right: 1rem; text-decoration: none; }}
  main {{ padding: 2rem; max-width: 900px; margin: auto; }}
  section {{ margin: 2rem 0; padding: 1rem 1.5rem; border-radius: 8px;
            background: rgba(128,128,160,.08); }}
  button {{ padding: .6rem 1.2rem; border: 0; border-radius: 6px; cursor: pointer;
           background: #6c63ff; color: white; font-size: 1rem; }}
  footer {{ text-align: center; padding: 1.5rem; color: rgba(128,128,160,.8); }}
</style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <nav>{nav_links}</nav>
  </header>
  <main>
    <button onclick="greet()">Say hello</button>
    <p id="hello"></p>
{section_blocks}
  </main>
  <footer>Generated by the Aashu Virtual Brain (learned: html)</footer>
  <script>
    function greet() {{
      document.getElementById('hello').textContent =
        'Hello from {title}! This site was built from the brain's learned html knowledge.';
    }}
  </script>
</body>
</html>
"""
        folder = self._project_path(name)
        path = os.path.join(folder, "index.html")
        with open(path, "w") as f:
            f.write(html)
        return True, f"Built website '{title}' at {path} ({len(sections)} sections, {theme} theme). Open in a browser to view."

    # ---------------------------------------------------------------
    # Flask web app (multi-file runnable project)
    # ---------------------------------------------------------------

    def build_webapp(self, name="My App", app_name="app", features=None, pages=None):
        ok, lang, err = self._gate("python")
        if not ok:
            return False, err
        name = _sanitize(name, "My App")
        app_name = _slug(_sanitize(app_name, "app"))
        features = [f.strip() for f in (features or "").split(";") if f.strip()] or ["Home"]
        pages = [p.strip() for p in (pages or "").split(";") if p.strip()] or features
        routes = "".join(
            f"\n@app.route('/{_slug(p)}')\ndef page_{_slug(p).replace('-', '_')}():\n"
            f"    return render_template('index.html', title='{_sanitize(p)}', app_name={app_name!r})\n"
            for p in pages
        )
        feature_list = ", ".join(features)
        app_py = f'''"""
{name} - a Flask web application generated by the Aashu Virtual Brain.
Features: {feature_list}
Run with: python {app_name}.py  (then open http://127.0.0.1:5000)
"""
from flask import Flask, render_template

app = Flask(__name__)


@app.route('/')
def home():
    return render_template('index.html', title='Home', app_name={app_name!r})
{routes}

if __name__ == '__main__':
    app.run(debug=True)
'''
        template_html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }} - {{ app_name }}</title>
<link rel="stylesheet" href="/static/style.css">
</head>
<body>
  <header><h1>{{ app_name }}</h1><nav><a href="/">Home</a></nav></header>
  <main>
    <h2>{{ title }}</h2>
    <p>Welcome to {{ title }}. This page is served by the Flask app generated from
       the brain's learned python knowledge.</p>
  </main>
  <footer>{{ app_name }} &mdash; generated by Aashu</footer>
</body>
</html>
"""
        style_css = """body { margin: 0; font-family: -apple-system, Segoe UI, Roboto, sans-serif;
       background: #f4f4f9; color: #22223b; }
header { background: #6c63ff; color: #fff; padding: 1rem 2rem; }
nav a { color: #fff; margin-right: 1rem; text-decoration: none; }
main { padding: 2rem; max-width: 800px; margin: auto; }
footer { text-align: center; padding: 1.5rem; color: #888; }
"""
        folder = self._project_path(name)
        files = {
            f"{app_name}.py": app_py,
            "templates/index.html": template_html,
            "static/style.css": style_css,
            "requirements.txt": "flask>=3.0\n",
        }
        for rel, content in files.items():
            full = os.path.join(folder, rel)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w") as f:
                f.write(content)
        return True, (f"Built Flask web app '{name}' at {folder} "
                      f"({len(pages)} pages: {', '.join(pages)}). "
                      f"Run: python {app_name}.py")

    # ---------------------------------------------------------------
    # CLI tool (single-file Python program)
    # ---------------------------------------------------------------

    def build_cli(self, name="tool", task="print a friendly message", args=None):
        ok, lang, err = self._gate("python")
        if not ok:
            return False, err
        name = _slug(_sanitize(name, "tool"))
        task = _sanitize(task, "print a friendly message")
        arg_defs = []
        arg_uses = []
        for i, a in enumerate((args or "").split(";")[:6]):
            a = a.strip()
            if not a:
                continue
            akey = _slug(a).replace("-", "_")
            arg_defs.append(f"    parser.add_argument('--{akey}', default='{_sanitize(a)}')")
            arg_uses.append(f"    print(f'  - {_sanitize(a)}: {{args.{akey}}}')")
        arg_uses_code = "\n".join(arg_uses) or "    print('  - no arguments provided')"
        cli = f'''#!/usr/bin/env python3
"""{name} - {task}

Generated by the Aashu Virtual Brain (learned: python).
Run with: python {name}.py [options]
"""
import argparse


def main():
    parser = argparse.ArgumentParser(description='{task}')
{chr(10).join(arg_defs)}
    args = parser.parse_args()
    print('=== {name} ===')
    print('Task: {task}')
{arg_uses_code}


if __name__ == '__main__':
    main()
'''
        folder = self._project_path(name)
        path = os.path.join(folder, f"{name}.py")
        with open(path, "w") as f:
            f.write(cli)
        return True, f"Built CLI tool '{name}' at {path} (task: {task}). Run: python {path}"

    # ---------------------------------------------------------------
    # React (Vite) web app (multi-file runnable project)
    # ---------------------------------------------------------------

    def build_reactapp(self, name="My App", app_name="app", features=None, pages=None):
        ok, lang, err = self._gate("reactjs")
        if not ok:
            return False, err
        name = _sanitize(name, "My App")
        app_name = _slug(_sanitize(app_name, "app"))
        features = [f.strip() for f in (features or "").split(";") if f.strip()] or ["Home"]
        pages = [p.strip() for p in (pages or "").split(";") if p.strip()] or features
        nav = " ".join(
            f'<li key="{_slug(p)}">{_sanitize(p)}</li>' for p in pages
        )
        feature_list = ", ".join(features)
        app_jsx = f"""import {{ useState }} from 'react';
import './index.css';

function App() {{
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <header>
        <h1>{name}</h1>
        <ul className="nav">
          {nav}
        </ul>
      </header>
      <main>
        <h2>Welcome</h2>
        <p>This React app was generated from the brain's learned reactjs knowledge.</p>
        <p>Features: {feature_list}</p>
        <button onClick={{() => setCount((c) => c + 1)}}>Count: {{{{count}}}}</button>
      </main>
    </div>
  );
}}

export default App;
"""
        main_jsx = "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App.jsx';\n\ncreateRoot(document.getElementById('root')).render(<App />);\n"
        index_html = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>%s</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.jsx"></script>
</body>
</html>
""" % name
        index_css = """:root { font-family: -apple-system, Segoe UI, Roboto, sans-serif; }
body { margin: 0; background: #f4f4f9; color: #22223b; }
.App { text-align: center; }
header { background: #6c63ff; color: #fff; padding: 1rem 2rem; }
.nav { list-style: none; display: flex; gap: 1rem; justify-content: center; padding: 0; }
button { padding: .6rem 1.2rem; border: 0; border-radius: 6px; background: #6c63ff; color: #fff; cursor: pointer; }
"""
        package_json = """{
  "name": "%s",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview" },
  "dependencies": { "react": "^18.3.1", "react-dom": "^18.3.1" },
  "devDependencies": { "@vitejs/plugin-react": "^4.3.1", "vite": "^5.4.0" }
}
""" % _slug(name)
        vite_config = """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({ plugins: [react()] });
"""
        folder = self._project_path(name)
        files = {
            "package.json": package_json,
            "vite.config.js": vite_config,
            "index.html": index_html,
            "src/main.jsx": main_jsx,
            "src/App.jsx": app_jsx,
            "src/index.css": index_css,
        }
        for rel, content in files.items():
            full = os.path.join(folder, rel)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w") as f:
                f.write(content)
        return True, (f"Built React web app '{name}' at {folder} ({len(pages)} pages: {', '.join(pages)}). "
                      f"Run: cd {folder} && npm install && npm run dev")

    def list_projects(self):
        if not os.path.isdir(self.output_dir):
            return []
        projects = []
        for name in sorted(os.listdir(self.output_dir)):
            path = os.path.join(self.output_dir, name)
            if os.path.isdir(path):
                files = []
                for root, _, fnames in os.walk(path):
                    for fn in fnames:
                        files.append(os.path.relpath(os.path.join(root, fn), path))
                projects.append({"name": name, "path": path, "files": files})
        return projects
