#!/usr/bin/env python3
"""greet - print a greeting

Generated by the Aashu Virtual Brain (learned: python).
Run with: python greet.py [options]
"""
import argparse


def main():
    parser = argparse.ArgumentParser(description='print a greeting')
    parser.add_argument('--name', default='name')
    args = parser.parse_args()
    print('=== greet ===')
    print('Task: print a greeting')
    print(f'  - name: {args.name}')


if __name__ == '__main__':
    main()
