"""
TaskBoard - a Flask web application generated by the Aashu Virtual Brain.
Features: auth, dashboard
Run with: python app.py  (then open http://127.0.0.1:5000)
"""
from flask import Flask, render_template

app = Flask(__name__)


@app.route('/')
def home():
    return render_template('index.html', title='Home', app_name='app')

@app.route('/home')
def page_home():
    return render_template('index.html', title='Home', app_name='app')

@app.route('/about')
def page_about():
    return render_template('index.html', title='About', app_name='app')


if __name__ == '__main__':
    app.run(debug=True)
